package view

import (
	"strings"
	"testing"

	"github.com/remin-dev/remin/internal/store"
	"github.com/remin-dev/remin/internal/testutil"
)

// 视图是真源的确定性投影：只含 active 可见条目，按类型分组，头标注重建方式
func TestAGENTSProjection(t *testing.T) {
	st := testutil.NewStore(t)
	ms := []*store.Memory{
		{ID: "mem_P", Type: store.TypePreference, Facet: "dev", Status: store.StatusActive,
			CapturedAt: store.NowTime(), ReviewedAt: store.NowTime(), Modified: store.NowTime(),
			Trust: store.TrustHumanVerified, Source: store.SourceAgent,
			Provenance: store.Provenance{Origin: "t", Ref: "t", Quote: "q"},
			Version:    store.FormatVersion, Body: "回复用中文"},
		{ID: "mem_D", Type: store.TypeDecision, Facet: "dev", Status: store.StatusActive,
			CapturedAt: store.NowTime(), ReviewedAt: store.NowTime(), Modified: store.NowTime(),
			Trust: store.TrustHumanVerified, Source: store.SourceAgent,
			Provenance: store.Provenance{Origin: "t", Ref: "t", Quote: "q"},
			Version:    store.FormatVersion, Body: "选 Postgres"},
		{ID: "mem_S", Type: store.TypeDecision, Facet: "dev", Status: store.StatusSuperseded,
			CapturedAt: store.NowTime(), ReviewedAt: store.NowTime(), Modified: store.NowTime(),
			Trust: store.TrustHumanVerified, Source: store.SourceAgent,
			Provenance: store.Provenance{Origin: "t", Ref: "t", Quote: "q"},
			Version:    store.FormatVersion, Body: "选 Mongo（已废弃）"},
	}
	for _, m := range ms {
		if err := st.SaveMemory(m); err != nil {
			t.Fatal(err)
		}
	}
	text, err := AGENTS(st, "")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(text, "generated by remin view") || !strings.Contains(text, "remin view --write") {
		t.Errorf("头应标注 generated 与重建命令:\n%s", text)
	}
	if !strings.Contains(text, "## preference") || !strings.Contains(text, "## decision") {
		t.Errorf("应按类型分组:\n%s", text)
	}
	if strings.Contains(text, "选 Mongo（已废弃）") {
		t.Error("superseded 不应出现在视图")
	}
	if !strings.Contains(text, "回复用中文") || !strings.Contains(text, "选 Postgres") {
		t.Error("active 条目应存在")
	}
	if !strings.Contains(text, "(人审)") {
		t.Error("trust 标签应随行")
	}
}

// facet 过滤
func TestAGENTSFacetFilter(t *testing.T) {
	st := testutil.NewStore(t)
	for _, m := range []*store.Memory{
		{ID: "mem_A", Type: store.TypeSemantic, Facet: "dev", Status: store.StatusActive,
			CapturedAt: store.NowTime(), ReviewedAt: store.NowTime(), Modified: store.NowTime(),
			Trust: store.TrustHumanVerified, Source: store.SourceAgent,
			Provenance: store.Provenance{Origin: "t", Ref: "t", Quote: "q"},
			Version:    store.FormatVersion, Body: "dev 条目"},
		{ID: "mem_B", Type: store.TypeSemantic, Facet: "life", Status: store.StatusActive,
			CapturedAt: store.NowTime(), ReviewedAt: store.NowTime(), Modified: store.NowTime(),
			Trust: store.TrustHumanVerified, Source: store.SourceAgent,
			Provenance: store.Provenance{Origin: "t", Ref: "t", Quote: "q"},
			Version:    store.FormatVersion, Body: "life 条目"},
	} {
		if err := st.SaveMemory(m); err != nil {
			t.Fatal(err)
		}
	}
	text, _ := AGENTS(st, "life")
	if strings.Contains(text, "dev 条目") || !strings.Contains(text, "life 条目") {
		t.Error("facet 过滤失效")
	}
}
