// Package view 视图投影（P2-H1）：AGENTS.md 等是真源的确定性投影，可随时删除重建。
// 仅用户显式 opt-in（--write）才落入 repo。
package view

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/remin-dev/remin/internal/store"
)

// AGENTS 生成 AGENTS.md 形态视图（按类型分组；排除不可见条目）
func AGENTS(st *store.Store, facet string) (string, error) {
	ms, err := st.ListMemories()
	if err != nil {
		return "", err
	}
	now := time.Now()
	byType := map[string][]*store.Memory{}
	for _, m := range ms {
		if m.Status != store.StatusActive {
			continue
		}
		if m.Verify != nil && m.Verify.Result == store.VerifyFailed {
			continue
		}
		if m.ExpiredAt(now) { // 与 inject/search 同口径：过期 recap 不进视图
			continue
		}
		if facet != "" && m.Facet != facet {
			continue
		}
		byType[m.Type] = append(byType[m.Type], m)
	}
	var types []string
	for t := range byType {
		types = append(types, t)
	}
	sort.Strings(types)

	var b strings.Builder
	b.WriteString("<!-- generated by remin view；本文件是真源（~/.remin/）的投影，重建: remin view --write <path> -->\n")
	b.WriteString("# 记忆（Remin 投影）\n\n")
	for _, t := range types {
		fmt.Fprintf(&b, "## %s\n\n", t)
		list := byType[t]
		sort.Slice(list, func(i, j int) bool { return list[i].ID < list[j].ID })
		for _, m := range list {
			line := firstLine(m.Body)
			fmt.Fprintf(&b, "- (%s) %s\n", store.TrustLabel(m.Trust), line)
		}
		b.WriteString("\n")
	}
	return b.String(), nil
}

func firstLine(s string) string {
	s = strings.TrimSpace(s)
	if i := strings.IndexAny(s, "\n"); i >= 0 {
		s = s[:i]
	}
	return s
}
