package extractor

import (
	"strings"
	"testing"

	"github.com/remin-dev/remin/internal/store"
)

func ev(role, text string, line int) Event {
	return Event{Role: role, Text: text, Line: line, SessionID: "abcdefgh1234"}
}

func TestExtractFiltersNoise(t *testing.T) {
	cands := Extract([]Event{
		ev("user", "<system-reminder>你被提醒了</system-reminder>", 1),
		ev("user", "Caveat: The messages below were generated by the user", 2),
		ev("user", "普通问题，不含指令", 3),
		ev("assistant", "", 4),
	})
	for _, c := range cands {
		if c.Expires == "" && strings.Contains(c.Body, "system-reminder") {
			t.Errorf("系统注入不应成为候选: %s", c.Body)
		}
		if strings.Contains(c.Body, "Caveat") {
			t.Errorf("Caveat 行不应成为候选: %s", c.Body)
		}
	}
}

func TestExtractUserDirectiveTypes(t *testing.T) {
	cands := Extract([]Event{
		ev("user", "记住：回复永远用中文", 1),
		ev("user", "部署前必须先跑迁移脚本", 2),
	})
	var pref, proc bool
	for _, c := range cands {
		if c.Type == store.TypePreference && strings.Contains(c.Body, "中文") {
			pref = true
		}
		if c.Type == store.TypeProcedural && strings.Contains(c.Body, "迁移") {
			proc = true
		}
	}
	if !pref || !proc {
		t.Errorf("偏好/程序性分类不对: pref=%v proc=%v (%+v)", pref, proc, cands)
	}
}

func TestExtractAssistantDecision(t *testing.T) {
	cands := Extract([]Event{
		ev("assistant", "我们决定选 Vitest 而不是 Jest，因为原生 ESM 支持", 7),
	})
	if len(cands) < 2 { // decision + recap
		t.Fatalf("应提取 decision 与 recap: %+v", cands)
	}
	if !strings.Contains(cands[0].Body, "Vitest") {
		t.Errorf("decision 正文不对: %s", cands[0].Body)
	}
	if cands[0].Provenance.Ref != "session#abcdefgh, line 7" {
		t.Errorf("ref 应指向行号: %s", cands[0].Provenance.Ref)
	}
}
