package extractor

import (
	"strings"
	"testing"

	"github.com/remin-dev/remin/internal/store"
)

func ev(role, text string, line int) Event {
	return Event{Role: role, Text: text, Line: line, SessionID: "abcdefgh1234"}
}

func TestExtractFiltersNoise(t *testing.T) {
	cands := Extract([]Event{
		ev("user", "<system-reminder>你被提醒了</system-reminder>", 1),
		ev("user", "Caveat: The messages below were generated by the user", 2),
		ev("user", "普通问题，不含指令", 3),
		ev("assistant", "", 4),
	})
	for _, c := range cands {
		if c.Expires == "" && strings.Contains(c.Body, "system-reminder") {
			t.Errorf("系统注入不应成为候选: %s", c.Body)
		}
		if strings.Contains(c.Body, "Caveat") {
			t.Errorf("Caveat 行不应成为候选: %s", c.Body)
		}
	}
}

func TestExtractUserDirectiveTypes(t *testing.T) {
	cands := Extract([]Event{
		ev("user", "记住：回复永远用中文", 1),
		ev("user", "部署前必须先跑迁移脚本", 2),
	})
	var pref, proc bool
	for _, c := range cands {
		if c.Type == store.TypePreference && strings.Contains(c.Body, "中文") {
			pref = true
		}
		if c.Type == store.TypeProcedural && strings.Contains(c.Body, "迁移") {
			proc = true
		}
	}
	if !pref || !proc {
		t.Errorf("偏好/程序性分类不对: pref=%v proc=%v (%+v)", pref, proc, cands)
	}
}

func TestExtractAssistantDecision(t *testing.T) {
	cands := Extract([]Event{
		ev("assistant", "我们决定选 Vitest 而不是 Jest，因为原生 ESM 支持", 7),
	})
	if len(cands) < 2 { // decision + recap
		t.Fatalf("应提取 decision 与 recap: %+v", cands)
	}
	if !strings.Contains(cands[0].Body, "Vitest") {
		t.Errorf("decision 正文不对: %s", cands[0].Body)
	}
	if cands[0].Provenance.Ref != "session#abcdefgh, line 7" {
		t.Errorf("ref 应指向行号: %s", cands[0].Provenance.Ref)
	}
}

// TestOriginAttributionAndFallback origin 归因：随源标注；空回退 claude-code（存量行为不变）
func TestOriginAttributionAndFallback(t *testing.T) {
	withOrigin := ev("user", "记住：构建走 pnpm", 1)
	withOrigin.Origin = "codex"
	cands := Extract([]Event{withOrigin})
	if len(cands) == 0 {
		t.Fatal("应产候选")
	}
	var typed, recap bool
	for _, c := range cands {
		if c.Expires == "" {
			typed = true
			if c.Provenance.Origin != "codex" {
				t.Errorf("typed 候选 origin 应随源 codex: %+v", c.Provenance)
			}
		} else {
			recap = true
			if c.Provenance.Origin != "codex" {
				t.Errorf("recap origin 应随批内来源: %+v", c.Provenance)
			}
		}
	}
	if !typed || !recap {
		t.Fatalf("应同时产 typed 与 recap: %+v", cands)
	}

	// 空 Origin 回退 claude-code
	fallback := Extract([]Event{ev("user", "记住：构建走 npm", 5)})
	for _, c := range fallback {
		if c.Provenance.Origin != "claude-code" {
			t.Errorf("空 origin 应回退 claude-code: %+v", c.Provenance)
		}
	}
}

// TestDeepOriginOfFollowsEventOrigin 深路径 origin 派生（随源 ·deep；空回退 claude-code·deep）
func TestDeepOriginOfFollowsEventOrigin(t *testing.T) {
	if got := deepOriginOf(Event{Origin: "dsh"}); got != "dsh·deep" {
		t.Errorf("随源派生: %s", got)
	}
	if got := deepOriginOf(Event{}); got != "claude-code·deep" {
		t.Errorf("空回退: %s", got)
	}
}
